# config.py

# Google Sheets Configuration
SERVICE_ACCOUNT_FILE = "service_account.json"
SHEET_ID = "1thzHWrVeue_TOkXoQQ0_mzWXICSFpVznB4kvUhDmchY"
PRODUCT_SHEET_NAME = "zepto_scraper"
PINCODE_SHEET_NAME = "Pincodes_Zepto"

# Google Drive Configuration
GDRIVE_SERVICE_ACCOUNT_FILE = "service_account.json"
GDRIVE_FOLDER_ID = "12D5bQ9pTcQeR71-Wn3C5c7Bul3eMI5t8"
NEW_GDRIVE_FOLDER_ID = "1L1SRNYcFTL4dqpBbHiYGdTtKnWZUqhv9"

# MongoDB Configuration
MONGO_URI = "mongodb://localhost:27017/"
MONGO_DB_NAME = "pinsight"
MONGO_COLLECTION_PRODUCTS = "products"
MONGO_COLLECTION_STORE_MAPPING = "zepto_store_mapping"

# API Configuration
MAX_RETRIES = 3
THREAD_POOL_SIZE = 3
RETRY_DELAY = 10

# Zyte Proxy Configuration
ZYTE_PROXY = {
    "http": "http://756c70b43e174b59b96af426cda9f345:@api.zyte.com:8011/",
    "https": "http://756c70b43e174b59b96af426cda9f345:@api.zyte.com:8011/"
}
ZYTE_CERT = "C:/Users/abhij/OneDrive/Documents/GitHub/pb zepto/zyte-ca.crt"

# Rotating User-Agents for scraping
CHROME_USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, lizyte-ca.crtke Gecko) Chrome/133.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36"
]

# OkHttp User-Agents for header builder
OKHTTP_USER_AGENTS = [
    "okhttp/4.9.3",
    "okhttp/4.9.2",
    "okhttp/4.10.0",
    "okhttp/5.0.0-alpha.2",
    "okhttp/4.9.1"
]

# Device models and brands for header builder
DEVICE_MODELS = [
    "sdk_gphone64_x86_64",
    "SM-G998B",
    "Pixel 7",
    "Pixel 6",
    "SM-A536B",
    "OnePlus9Pro",
    "M2101K6G"
]

DEVICE_BRANDS = [
    "google",
    "samsung",
    "oneplus",
    "xiaomi",
    "oppo",
    "vivo",
    "realme"
]

# Compatible components string for Zepto headers
COMPATIBLE_COMPONENTS = (
    "SAMPLING_FOR_COUPON_MOV_ENABLED,CONVENIENCE_FEE,RAIN_FEE,EXTERNAL_COUPONS,"
    "STANDSTILL,BUNDLE,MULTI_SELLER_ENABLED,PIP_V1,ROLLUPS,SAMPLING_ENABLED,"
    "ETA_NORMAL_WITH_149_DELIVERY,ROLLUPS_UOM,SAMPLING_V2,RE_PROMISE_ETA_ORDER_SCREEN_ENABLED,"
    "RECOMMENDED_COUPON_WIDGET,NZS_CAMPAIGN_COMPONENT,ETA_NORMAL_WITH_199_DELIVERY,"
    "NEW_FEE_STRUCTURE,PHARMA_ENABLED,REWARDS_WIDGET_MISSION_V2,GAMIFICATION_ENABLED,"
    "DYNAMIC_FILTERS,HOMEPAGE_V2,COUPON_WIDGET_CART_REVAMP,AUTOSUGGESTION_PIP,NEW_ETA_BANNER,"
    "CART_TABBED_WIDGET,BPC_GROUP_DETAILS,IS_DYNAMIC_NZS_SUPPORTED,ZEPTO_THREE,"
    "RERANKING_QCL_RELATED_PRODUCTS,AUTO_COD_ORDER_ENABLED,PAAN_BANNER_WIDGETIZED,"
    "SINGLE_CLICK_COD_PAYMENT,AUTOSUGGESTION_PAGE_ENABLED,COUPON_UPSELLING_WIDGET,"
    "DELIVERY_UPSELLING_WIDGET,CART_BOX_MODEL_WIDGETS,NEW_WALLET_INFO,REFERRAL_P2,"
    "PDP_TOP_PRODUCT_BANNER,AUTOSUGGESTION_AD_PIP,VERTICAL_FEED_PRODUCT_GRID,"
    "SWAP_LOGIC_CART_PAGE,3x3_PRODUCT_GRID_WIDGET,BOTTOM_NAV_FULL_ICON,"
    "RECOMMENDED_PRODUCTS_VERTICAL_GRID,OOS_RECOMMENDATIONS,PRE_SEARCH_2.0,"
    "NEW_BILL_INFO,ZEPTO_PASS,ZEPTO_PASS:3,ZEPTO_PASS_RENEWAL,"
    "MANUALLY_APPLIED_DELIVERY_FEE_RECEIVABLE,AUTO_COD_ORDER_ENABLED_V2,"
    "PLP_ON_SEARCH,NEW_ROLLUPS_ENABLED,RICH_PRODUCT_CARD_GRID,RPCC_TIMER,"
    "MARKETPLACE_REPLACEMENT,MARKETPLACE_CATEGORY_GRID,VBD,CROSS_SELL_V2,"
    "COUPON_BOTTOM_STRIP,TABBED_CAROUSEL_V2"
) 